### ISSUE TITLE
Неправильные координаты Мурманской области

### ISSUE THREAD

**Issue by bragovo** [kalyabin/russian-map#2]
Туда попала вся РФ и Сахалин. И похоже часть остовов из Архангельской.
Для основной области path я вырезал: `203.67,209.45l8,7.21-.38,3-.87,2.46,1.79,1.79,2.79-.66,1.75,1,2.08-.17h0l-.66-3.67,1.58-1.58,1.08-2.92,2.34,2.34-1.92,1.91L220.5,224l2.33,1,1.17,6.17,2.17,3.67,1.16,3.33,1.5,3.5,3.17,3.17v4.5l3.08,3.08,4.92,2.75,4.5,1.67,5.16-1h4.67l4.42-4.42,2.91-5.08.67-6,.17-3.67-2.92-2.92-.08-5.08-1-2.33.83-4.17v-4.83L258,212.62l-2.75-2.75V206l-2.42-1.16v-3.5l-2.17-2.17-2.83-1.5v-3.17l-.83-3.17,1.75-1.75,1.92,1.92,1.83,1.17-.83-3V187l-4-.17-2.84.34.7-3.5-2.86,2-2.34-2.34H237.5l-4.83-1.83-7,3.5-5.34,2.67v9l-2.66,4.67h-8.5l-5.09,5.08-.41,3.08h0`

Но с островами не стал разбираться :/

**Comment by bragovo** [comment]
И заодно у Питера `М130` стоит.

**Comment by kalyabin** [comment]
Благодарю за информацию. 

Можете сделать pr, чтобы посмотреть что получается?

**Comment by bragovo** [comment]
Да, только может сделать файл регионов не сжатым? А то ориентироваться в нем сложно, а кому нужно для продакшна сам сожмет его как ему нужно.

**Comment by bragovo** [comment]
Добавил, но если не распаковать, вообще ничего непонятно, поэтому я сначала beautify сделал, потому поправил.

**Comment by bragovo** [comment]
С Питером тоже что-то не так, там такая небольшая область, а координат на нее как на 10 Мурманских областей, видимо очень высокая точность. Я потом в AI посмотрю чтобы меньшими координатами его описать.

**Comment by kalyabin** [comment]
@bragovo можем закрывать баг?

**Comment by bragovo** [comment]
Да, вполне, спасибо.
